openapi: 3.0.0
info:
  title: Login (Auth)
  version: '1.0'
servers:
  - url: 'https://mindverse-backend.herokuapp.com'
    description: Mindverse backend server
paths:
  /auth/local:
    parameters: []
    post:
      summary: ''
      operationId: post-auth-local
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  jwt:
                    type: string
                    minLength: 1
                  user:
                    type: object
                    required:
                      - id
                      - username
                      - email
                      - provider
                      - role
                      - created_at
                      - updated_at
                    properties:
                      id:
                        type: number
                      username:
                        type: string
                        minLength: 1
                      email:
                        type: string
                        minLength: 1
                      provider:
                        type: string
                        minLength: 1
                      confirmed: {}
                      blocked: {}
                      role:
                        type: object
                        required:
                          - id
                          - name
                          - description
                          - type
                        properties:
                          id:
                            type: number
                          name:
                            type: string
                            minLength: 1
                          description:
                            type: string
                            minLength: 1
                          type:
                            type: string
                            minLength: 1
                      created_at:
                        type: string
                        minLength: 1
                      updated_at:
                        type: string
                        minLength: 1
                required:
                  - jwt
                  - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                password:
                  type: string
        description: Identifier can be eithher username or email
      description: User login with authenticated access.
components:
  schemas:
    User:
      description: ''
      type: object
      properties:
        jwt:
          type: string
          minLength: 1
        user:
          type: object
          properties:
            id:
              type: number
            username:
              type: string
              minLength: 1
            email:
              type: string
              minLength: 1
            provider:
              type: string
              minLength: 1
            confirmed: {}
            blocked: {}
            role:
              type: object
              properties:
                id:
                  type: number
                name:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
                type:
                  type: string
                  minLength: 1
              required:
                - id
                - name
                - description
                - type
            created_at:
              type: string
              minLength: 1
            updated_at:
              type: string
              minLength: 1
          required:
            - id
            - username
            - email
            - provider
            - role
            - created_at
            - updated_at
      required:
        - jwt
        - user
      x-examples:
        example-1:
          jwt: string
          user:
            id: 0
            username: string
            email: string
            provider: string
            confirmed: null
            blocked: null
            role:
              id: 0
              name: string
              description: string
              type: string
            created_at: string
            updated_at: string
